config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  resources: players

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end

  def show
  	@player = PLayer.find_by(id: params[:id])
  end

  def create
  	@player = Player.new(player_params)
  	if @player.save
  		redirect_to root_path
  	end
  end

  def edit
  	@player = PLayer.find_by(id: params[:id])
  end

  def update
  	@player = Player.find_by(id: params[:id])
  	@player.update(player_params)
  	if @player.save
  	redirect_to	player_path(@player.id)
  end

  def delete
  	
  end

  private
  player_params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>Players#index</h1>
<p>Find me in app/views/players/index.html.erb</p>

app/views/players/new.html.erb
<%= form_for @player, url: player_path  do |f| %>
   <%= f.text_field :nickname %><br>
  <%= f.text_field :rank %><br>
  <%= f.text_field :charisma %><br>
  <%=f.text_field :wisdom %>
  <%= f.submit "Create" %>
<% end %>

app/views/players/show.html.erb
<p>
	<%= @player.nickname %> <br />
	rank: <%= @player.rank %><br />
	charisma: <%= @player.charisma %><br />
</p>

<p>
	<%= link_to 'Edit', edit_player_path(@player.id) %><br />
	<%= link_to 'Destroy',player_path(@player.id), method: :delete %>
</p>